# Generated by Django 2.1.7 on 2019-03-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peopel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('sdt', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('passwd', models.CharField(max_length=255)),
            ],
        ),
    ]
