from django.db import models
import datetime
from django.db.models.signals import pre_save
from django.contrib.auth.models import User
from django.utils import timezone


# Create your models here.

#User model is auto-generated by Django, it's content all of thing we need :D

#This class using for Profile of User
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key = True)
    avatar_upload = models.ImageField(upload_to="UserProfile/") #this field using for upload image and convert this image to avatar_link
    avatar_link = models.CharField(max_length = 255)
    headline = models.CharField(max_length = 255)
    biography = models.TextField()

    def __str__(self):
        return self.user.username


class Course(models.Model):
    name = models.CharField(max_length = 255)
    img_cover = models.FileField(upload_to="cover/", blank = True)
    cover_link = models.CharField(default= "Link is empty", max_length = 1024, blank = True)
    create_date = models.DateTimeField( default = timezone.now);
    description = models.TextField();
    students = models.ManyToManyField("auth.User", related_name='course', blank = True)
    views = models.IntegerField(default= 0)
    LANGUAGE_CHOICES = (
        ("Tiếng Việt", "VN"),
        ("Tiếng Anh", "EN")
    )
    language = models.CharField(max_length = 255, choices = LANGUAGE_CHOICES, default= LANGUAGE_CHOICES[0])
    LEVEL_CHOICES = (
        ("Tất cả", "All"),
        ("Mới học", "Beginer"),
        ("Nâng cao", 'Junior')
    )
    level = models.CharField(max_length = 255, choices=LEVEL_CHOICES,default= LEVEL_CHOICES[0])
    def __str__(self):
        return self.name

class Category(models.Model):
    ten_danh_muc = models.CharField(max_length = 255)
    khoa_hoc = models.ManyToManyField(Course, related_name="categories", blank=True)

    def __str__(self):
        return self.ten_danh_muc

class Video(models.Model):
    khoa_hoc = models.ForeignKey(Course, related_name= "video", on_delete= models.CASCADE)
    video_name = models.CharField(max_length = 255, default = "No name")
    link_video = models.URLField()
    duration = models.DurationField(max_length = 255)
    video_id = models.CharField(max_length = 255)

    def __str__(self):
        return self.video_name

def save_video_function(sender, instance, *args, **kwargs):
    import youtube_dl
    print("Begin save...")
    url = instance.link_video
    ydl_opts = {}
    with youtube_dl.YoutubeDL(ydl_opts) as ydl:
        meta = ydl.extract_info(
            url, download=False)
    duration = int(meta['duration'])
    instance.duration = datetime.timedelta(seconds = duration)
    instance.video_id = meta['id']
    print("Complete")






