from django.db import models
from django.contrib.auth.models import User
# Create your models here.

#User model is auto-generated by Django, it's content all of thing we need :D

#This class using for Profile of User
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key = True)
    avatar_upload = models.ImageField(upload_to="UserProfile/") #this field using for upload image and convert this image to avatar_link
    avatar_link = models.CharField(max_length = 255)
    headline = models.CharField(max_length = 255)
    biography = models.TextField()

    def __str__(self):
        return self.user.username

