# Generated by Django 2.1.7 on 2019-03-24 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Peopel',
            new_name='Account',
        ),
    ]
