# Generated by Django 2.1.7 on 2019-04-10 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apps', '0003_auto_20190326_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_danh_muc', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('img_cover', models.FileField(blank=True, upload_to='cover/')),
                ('cover_link', models.CharField(blank=True, default='Link is empty', max_length=1024)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('views', models.IntegerField(default=0)),
                ('language', models.CharField(choices=[('Tiếng Việt', 'VN'), ('Tiếng Anh', 'EN')], default=('Tiếng Việt', 'VN'), max_length=255)),
                ('level', models.CharField(choices=[('Tất cả', 'All'), ('Mới học', 'Beginer'), ('Nâng cao', 'Junior')], default=('Tất cả', 'All'), max_length=255)),
                ('students', models.ManyToManyField(blank=True, related_name='course', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(default='No name', max_length=255)),
                ('link_video', models.URLField()),
                ('duration', models.DurationField(max_length=255)),
                ('video_id', models.CharField(max_length=255)),
                ('khoa_hoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='apps.Course')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='khoa_hoc',
            field=models.ManyToManyField(blank=True, related_name='categories', to='apps.Course'),
        ),
    ]
